### ISSUE TITLE
Key Attributes not showing when using serenity-reportportal-integration version 1.4.3

### ISSUE THREAD

**Issue by Kumar-Manish1** [Invictum/serenity-reportportal-integration#134] opened 2021-02-22 09:45 UTC
1. Key and value attributes are appeared when we use invictum dependency version 1.5.5 or 1.5....onwards but build of sanity is getting failed due to build issue and it looks like all test cases are being passed and no result is showing on the report portal.

2. when we use version 1.4....onwards then the sanity is getting pass correctly but key and value attributes are not showing .

**Comment by Invictum** [comment] 2021-02-22 13:00
Hi @Kumar-Manish1,

What version of Report Portal server side is used?

**Comment by Kumar-Manish1** [comment] 2021-02-22 13:33
Report Portal version is 5.3.3

**Comment by Invictum** [comment] 2021-02-22 13:55
So first of all integration of 1.5.x+ must be used, because it compatible with RP 5.
Next I assume legacy attributes are used, but to make sure can you provide an example of tests run command? Or if possible example of project that reproduces an issue.

**Comment by Kumar-Manish1** [comment] 2021-02-22 13:59
ok so when I am using 1.5.5 version then key attributes are appeared but after that I am facing build failure issue just because of this errro Exception in thread "Thread-0" java.lang.NullPointerException
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.lambda$get$0(ReportLaunchProvider.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Kumar-Manish1** [comment] 2021-02-22 14:00
And I am using this command to run the test 
mvn clean verify -Dchrome.switches="--headless,--no-sandbox,--disable-dev-shm-usage" -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dcucumber.options="src/test/resources/features" -Denv=$ENV_NAME

**Comment by Invictum** [comment] 2021-02-22 16:07
It is definitely a bug on integration code side. And it will be fixed with next release.
Thanks @Kumar-Manish1

**Comment by Kumar-Manish1** [comment] 2021-02-23 06:55
Hi @Invictum, one more thing in other projects reports are not showing after updating version to 1.5.5 and it gives error 
java.lang.NullPointerException and due to this build is also getting failed.
![Screenshot from 2021-02-23 12-23-56](https://user-images.githubusercontent.com/58431014/108810891-22a8c580-75d2-11eb-9844-d601d0f829fd.png)

**Comment by Invictum** [comment] 2021-03-21 16:54
@Kumar-Manish1 
Issue can't be reproduced with given info and will be closed. Feel free to create a new one with more details if error persists.

**Closed as completed by Invictum** 2021-03-21 16:54 UTC
Labels: bug
