### ISSUE TITLE
Tag visualisation for Scenario Outline examples in Report Portal Tool

### ISSUE THREAD

**Issue by aprado94** [Invictum/serenity-reportportal-integration#152] opened 2022-10-04 11:43 UTC
I am using Serenity with Cucumber and what I am trying to do is dividing the scenario examples with different tags like in the following image:

![image](https://user-images.githubusercontent.com/50696508/193796766-d1ca4cd7-5c72-448a-b735-d8952ff3a2d4.png)

When the tests are uploaded to the Report Portal something strange seems to be happening related to the tag management. In my scenario outline examples, I used 3 different tags for each test example: **example1**, **example2** and **example3**. But when I check  the tests in the Report Portal, the first one has the correct tag, but the following examples have their corresponding tag and the previous example tag.

![image](https://user-images.githubusercontent.com/50696508/193806608-b67bccf1-9a4c-4288-9b13-4591d6bf9aa8.png)

What I was expecting to happen, was that each test example would have its related tag attached and not taking the attribute value from itself and all the previous ones, so in this case 3 examples will be tagged as **example1**, 2 as **example2**, and 1 as **example3**.

Could this be a bug related to this integration?

**Comment by grey-rain** [comment] 2023-10-22 18:22
@aprado94 I know its been a while, but I made some digging here.
The issue you face comes from Serenity itself: they do not distinct story-level tags (long TTL) from example-level tags (short TTL) in net.thucydides.model.domain.TestOutcome#addTag and it just accumulates all tags it faced during execution. In can be seen in native Serenity report, they also have this tag applied to all 3 tests.
![image](https://github.com/Invictum/serenity-reportportal-integration/assets/14541351/4535a4f1-e58f-4425-9f54-fe8bca2c1698)
If you're still interested in having this issue resolved - please report it to Serenity team (https://github.com/serenity-bdd/serenity-core/issues/new/choose) or propose a fix.
Integration will be fixed as soon as the issue is fixed in Serenity and new Serenity version is wrapped into integration.

**Closed as completed by grey-rain** 2023-10-22 18:22 UTC
Labels: serenity bug
