### ISSUE TITLE
NPE using CucumberWithSerenity

### ISSUE THREAD

**Issue by doomobou** [Invictum/serenity-reportportal-integration#59] opened 2019-02-24 11:48 UTC
I'm trying to setup Report Portal integration on my project that uses Serenity and Cucumber (@RunWith(CucumberWithSerenity.class)).

However, when launching tests, the first test itself passes, but I get NPE in the Runner class right after it:
`java.lang.NullPointerException
        at com.github.invictum.reportportal.handler.FlatHandler.finishTest(FlatHandler.java:91)
        at com.github.invictum.reportportal.ReportPortalListener.testFinished(ReportPortalListener.java:50)
        at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:300)
        at cucumber.runtime.formatter.SerenityReporter.handleTestCaseFinished(SerenityReporter.java:267)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$2(SerenityReporter.java:117)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.TestCase.run(TestCase.java:65)
        at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
`
And when launching a test suite with multiple tests, only the first test is finished, others don't launch due to NPE in Runner.

I've tried multiple versions, but current ones are:
serenity 2.0.20
serenity-cucumber 1.9.21
serenity-reportportal-integration 1.3.0

Please see the sample project (attached) where I was able to reproduce the issue on minimal configuration for further info. Launch it with "mvn clean verify"

[serenitycucumberreportportalsample.zip](https://github.com/Invictum/serenity-reportportal-integration/files/2897842/serenitycucumberreportportalsample.zip)

The runs appear in my local Report Portal, but again, they contain only the first test
![image](https://user-images.githubusercontent.com/42808499/53298745-236fbb00-3843-11e9-8ec2-ea99a1869307.png)

Looking forward to hearing back from you.

**Comment by Invictum** [comment] 2019-03-01 19:49
@doomobou 
Thanks for reported issue. I've investigated it and found a root cause - looks Serenity core produce `TestOutcome` differently for UI and non UI tests.
Your example project is API test, but you defined `StepDefs` class as UI ready with pages injection
```
    public StepDefs (Pages pages) {
        super(pages);
    }
```
With default constructor in `StepDefs` NPE exception won't be rised.

Unfortunately from this point an old Serenity bug is in effect https://github.com/serenity-bdd/serenity-core/issues/707

Potentially it is possible to avoid Serenity issue in integration, but this require some time and investigation.

**Comment by doomobou** [comment] 2019-03-14 09:56
Sorry for the long wait.
Fixed my example according to your comments.
In my actual project 95% of the tests are in browser, in the new version I'm still getting the same NPE after the first successful test. Report Portal receives the run, but it only contains the first test as well.
I'm guessing that now it is due to that Serenity Junit bug you previously mentioned

[serenitycucumberreportportalsample.zip](https://github.com/Invictum/serenity-reportportal-integration/files/2965755/serenitycucumberreportportalsample.zip)
run with 'mvn -Dwebdriver.chrome.driver="path_to_chromedriver" clean verify'

**Comment by Invictum** [comment] 2019-03-14 14:21
@doomobou

I am planning to change integration recording approach to avoid Setenity issues. So you may try version 1.4.0 when ot will be ready.

**Comment by Invictum** [comment] 2019-04-13 20:23
@doomobou 

I checked your issue one more time and actually find several issue that causes it. All of them connected to Serenity Cucumber configuration itself:
 - you are using really old version of Serenity, I recommend to use latest versions
 - you mixed up definitions (glue) and step entities (scenario steps). Serenity handles them in a different way and has mandatory folders structure. Check [Serenity manual](http://thucydides.info/docs/serenity-staging/#_serenity_with_cucumber) for more details - especial section 6.2.3

Here is fixed project that able to run and push reports to RP: [serenitycucumberreportportalsample.zip](https://github.com/Invictum/serenity-reportportal-integration/files/3076706/serenitycucumberreportportalsample.zip)

I'm closing this issue. Feel free to create another one in case of other issues.

**Closed by Invictum** 2019-04-13 20:23 UTC
Labels: clarification required
